import type {Metadata} from "next";
import {Geist, Geist_Mono, Chewy} from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const chewy = Chewy({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-chewy",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${chewy.variable} antialiased`}
            >
                <header>
                    <Navbar />
                </header>
                {children}
            </body>
        </html>
    );
}
